export const colors = {
  heavyBackground: "#282f39",
  heavyBackgroundLightShift: "#48515c",
  heavyBackgroundTrans: "rgba(40, 47, 57, 0.2)",
  mainAccent: "#ca0d0d",
  mainAccentLightShift: "#eb1818",
  mainAccentTrans: "rgba(202, 13, 13, 0.2)",
  lightest: "#ffffff",
  inputBgr: "#d9dada33",
  buttonHover: "#292f3a",
  almostLight: "#F5F5F5",
};

export const fonts = {
  opacity: "0.8",
  bold: "700",
  regular: "400",
  headlineSize: "28px",
  headlineHeight: "35px",
  midHeadlineSize: "42px",
  midHeadlineHeight: "52.5px",
  largeHeadlineSize: "52px",
  largeHeadlineHeight: "65px",
  secondHeadlineSize: "22px",
  secondHeadlineHeight: "30px",
  subtitleSize: "18px",
  subtitleHeight: "25px",
  midSubtitleSize: "22px",
  midSubtitleHeight: "35px",
  sDescription: "13px",
  sDescriptionHeight: "22px",
  smallSubtitle: "14px",
  smallSubtitleHeight: "20px",
};
